<!DOCTYPE html>
<html lang="en">
<!-- Head. Css.  -->
<head>
    <link rel="stylesheet" href="/css/login.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<?php
include "tpl/head.phtml";
?>
</head>
<!-- End Head. Css.  -->
<title>Test task for scandiweb - Add page</title>
<body>
<!-- NAVBAR-->
<!-- END of NAVBAR -->
<div class="container">
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <h3>Sign In</h3>
                <div class="d-flex justify-content-end social_icon">
                    <span><i class="fab fa-facebook-square"></i></span>
                    <span><i class="fab fa-google-plus-square"></i></span>
                    <span><i class="fab fa-twitter-square"></i></span>
                </div>
            </div>
            <div class="card-body">

            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-center links">
                    ERROR<a href="/login/register">Register</a>
                </div>
                <div class="d-flex justify-content-center">
                    <a href="/">Go to Login Page</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Vendor scripts -->
<script src="/vendor/jquery.min.js"></script>
<!-- My script -->
<script src="/js/script.js"></script>
<!-- Footer -->
<footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">&copy; 2019 For Scandi Web Test</p>
    <ul class="list-inline">
        <li class="list-inline-item"><a href="/">Main</a></li>
        <li class="list-inline-item"><a href="/add/">Add Form</a></li>
    </ul>
</footer>
</body>
</html>